services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: mnemocast_admin
      POSTGRES_PASSWORD: mnemocast_password
      POSTGRES_DB: mnemocast_db
    ports:
      - "5433:5432"
