// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ChannelID string
	Title     string
	AddedAt   pgtype.Timestamptz
}

type Video struct {
	VideoID      string
	ChannelID    string
	Title        string
	Url          string
	IsSummarized bool
	PublishedAt  pgtype.Timestamptz
}
