// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
)

const createChannel = `-- name: CreateChannel :exec
INSERT INTO channels (channel_id, title)
VALUES ($1, $2)
ON CONFLICT (channel_id) DO NOTHING
`

type CreateChannelParams struct {
	ChannelID string
	Title     string
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) error {
	_, err := q.db.Exec(ctx, createChannel, arg.ChannelID, arg.Title)
	return err
}

const createSummary = `-- name: CreateSummary :exec
INSERT INTO summaries (video_id, summary_text)
VALUES ($1, $2)
ON CONFLICT (video_id) DO NOTHING
`

type CreateSummaryParams struct {
	VideoID     string
	SummaryText string
}

func (q *Queries) CreateSummary(ctx context.Context, arg CreateSummaryParams) error {
	_, err := q.db.Exec(ctx, createSummary, arg.VideoID, arg.SummaryText)
	return err
}

const createVideo = `-- name: CreateVideo :exec
INSERT INTO videos (video_id, channel_id, title, url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (video_id) DO NOTHING
`

type CreateVideoParams struct {
	VideoID   string
	ChannelID string
	Title     string
	Url       string
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) error {
	_, err := q.db.Exec(ctx, createVideo,
		arg.VideoID,
		arg.ChannelID,
		arg.Title,
		arg.Url,
	)
	return err
}
